### ISSUE TITLE
Pressing 'A' crashes on fresh install

### ISSUE THREAD

**Issue by frenata** [camdenb/DnD-Map-Creator#23]
After a fresh install, opening up the program and pressing 'A' crashes the program with the following error:

"main.lua:210:bad arguement 1 to 'print' (string expected, got nil)

Traceback
[c] in function 'print'
main.lua:210 in function 'draw'
[c] in function 'xpcall'

Possibly related: pressing 'S' doesn't appear to save, but exits the program after a few seconds with no message.

**Comment by camdenb** [comment]
I think I fixed this. I'll test it on some VMs but I'd appreciate if you could tell me if the latest commit fixed the issue. :)

**Comment by frenata** [comment]
Will do. I'm on a different machine at the moment, but if I can get LOVE installed I'll give it a whirl. Was this system/architecture specific, or just something that would only be an issue to a fresh clone?

**Comment by frenata** [comment]
'A' doesn't crash, but it doesn't do anything at all (reasonable if there are no maps save, but some kind of message _could_ be nice).

However 'S' still silently closes the program without error after a few seconds, and subsequent runs fo the program still have 'A' not performing any function. I'll have to try this on a different platform to see what the intended behavior is, but I'm guessing some kind of dialog?

Also, let me know if you prefer bugs/etc. on your google form, I was guessing you set that up for folks who weren't github users.

**Comment by camdenb** [comment]
It was an issues for fresh clones, because the save directory didn't exist even after saving the map, so it was just a matter of creating the save directory if it didn't exist already (and preventing A from trying to load anything if there wasn't anything to load).

**Comment by camdenb** [comment]
And yeah, I prefer Github issues :)

**Comment by camdenb** [comment]
@frenata Huh, I must've missed the meat of your last comment. I'll look into the issue some more. What OS are you using?

**Comment by frenata** [comment]
Archlinux

~~Where is the saves directory meant to be created?~~
I presume it's this line, in HelperFunctions.lua:10

``` lua
    love.filesystem.write('/maps/' .. os.date('%m-%d-%Y_%I%p-%M%S') .. '.txt', saveStr)
```

Checking just now, I _do_ have a maps directory present at ~/.local/share/DnD-Map-Creator/maps/, but it's empty. That's a pretty common user app data directory. I can do more poking around with LOVE, since it doesn't look like you're doing anything fancy, just leaning on their save functions.

**Comment by camdenb** [comment]
Huh. Maybe it's an issue with `os.date()`? That's the only OS-specific part of the code. I'll play around with it in Ubuntu and see what I can do.

**Comment by camdenb** [comment]
Damn, I'm getting the same issue on a fresh install of Lubuntu. Weird.

**Comment by camdenb** [comment]
Ok, the issue isn't with saving itself... it's with **what's** being saved. If I change the file to be saved from `saveStr` to something like `"test text"` then it saves just fine. Maybe Linux is preventing Love2D from writing too much data at a time? It's not uncommon for `saveStr` to be >200kb (which admittedly isn't **that** big). Huh.

**Comment by frenata** [comment]
heh, I'd narrowed it down to that as well. right now in my local copy I have the filename static and printlines immeidately before and after the call to love.filesystem.write, and the second print never triggers, so something is up with Grid:gridToString

**Comment by camdenb** [comment]
Glad to see we're on the same page :)
It's definitely the size of the grid being saved that's the issue. I resized the grid to 10x10 instead of 150x150 and it saved no problem.

**Comment by camdenb** [comment]
100x100 saves. Gonna test some more values.

**Comment by camdenb** [comment]
Wow, this is fascinating. 149x149 works perfectly fine, but 150x150 it freaks out and crashes. I really can't explain this.

**Comment by frenata** [comment]
commenting out Grid.lua:136

```
            str = str .. state .. '000000000000'
```

Solves the issue entirely. I'm not entirely sure what that line is supposed to be doing, though. (But I presume something important)

**Comment by camdenb** [comment]
The line sets that 13-character string (representing a cell's state and it's rgba color) to 13 0s if the state (filled vs not filled) is 0. It's probably not the best way of doing saving, but without that line it doesn't save the empty cells, resulting in one column of filled in cells on the top left of the map. I suppose I could save some space by skipping cells with state 0 when loading the grid, although that wouldn't remove the mysterious save limit (but it would raise the limit, of course).

**Comment by camdenb** [comment]
Love has an option to limit the size of the file saved. When limiting the 149x149 save to 100 bytes, it saves (as expected). But once again, when saving the 150x150 (and limiting it to 100 bytes) it crashes the program. OH, you know, it might have something to do with the _memory_ limit. Okay, yeah, that's what's happening. I'm guessing Linux is straight up running out of RAM. 

`top` shows me that when trying to save, love uses >25% of the RAM. That shouldn't be enough to crash the program though, right? Either way, I have to optimize the saving algo.

**Comment by camdenb** [comment]
Okaaay okay so I think it's luajit causing the issue. 
https://love2d.org/forums/viewtopic.php?f=4&p=180105

Not sure why there's a distinction between 149 and 150, the calculated sizes aren't _that_ different.

**Comment by frenata** [comment]
Sounds like you're zeroing in on the problem/solution. :) Unfortunately without experience in lua or luajit, there's not much more I can do to help other than verifying fixes.

Are the files/data really so large that's it running up against those kinds of memory limits though? It doesn't _seem_ like they'd be super large.

I guess a possible workaround is to store the Grid into a string in chunks? Or is there some builtin/more optimized serialization package you can use to save the Grid instead of building a string?

**Comment by camdenb** [comment]
Fixed it! Thanks so much for your help!

Instead of storing the whole grid data into a string, then writing the string to a file, it now it directly appends the file with the 13 char data. I could (and should) adjust this to maybe append at the end of every row to speed up saving, but for now I'm just happy that it works :) :ok_hand: 

edit: it works for me at least, please let me know if you're still having issues. Pertinent commit is af1c2e7

**Comment by frenata** [comment]
On the linux chrooted chromebook I'm sitting on at the moment, it works for a long while and finally prints the console message "cancelled", then the program goes back to normal operation. I can watch the file being appended to over time, and both times I've tried it finally quits when the file grows to exactly 292500 bytes.

Admittedly this isn't the most powerful machine ever, so I'll try later on my main workstation. Of course, this is what I generally use as my mobile DM platform. I'll try cranking down the grid size to see if that allows for working saves/loads.

Edit: On further examination, it does appear to be working despite the console message "cancelled". I can save and load separate maps appropriately.

**Comment by camdenb** [comment]
@frenata I made saving waaaaay more efficient (by saving the positions of cells that were filled instead of saving the whole damn grid), and now it saves in a jiffy. Saved a 1500x1500 grid w/ no lag. Now, if you were to fill the whole grid _then_ try to save, that's a different story. But it's fixed for normal use :)
