### ISSUE TITLE
Failure to find lib/lube/lube

### ISSUE THREAD

**Issue by frenata** [camdenb/DnD-Map-Creator#24]
Possible this is system specific, but on linux for me, the program fails to start entirely with an error on line 4: "module 'lib/lube/lube' not found.

Looking at the directory structure, changing the require to read 'lib/LUBE/LUBE' fixed the issue.

**Comment by camdenb** [comment]
Fixed in 2737802

Thanks! Interesting that OS X ignores case while Linux doesn't.
